### ISSUE TITLE
Builder lose connections between nodes

### ISSUE THREAD

**Issue by mihha** [baptisteArno/typebot.io#62] opened 2022-05-25 06:03 UTC
Hi,

I have started to work with self-hosted typebot extensively and have encounter a problem with the builder

You can see the issue in the following video, since I don't know how to better explain it
https://xbackbone.mihha-hosting.com/soJo9/RApaGIre83.mp4

It is visible in bots that have numerous nodes and elements

This is not visible in your example bot (Lead Generation bot as an example)

**Comment by mihha** [comment] 2022-05-25 18:16
That can be a workaround, but I couldn't find a way to forward variables and their content from one bot to another

I have a complex bot and using your workaround, I should be able to collect variable content in one bot and forward that variable and content to another bot

Maybe I just couldn't find a way?

**Comment by mihha** [comment] 2022-05-25 18:44
OK. I get it

I have to use the same variable names for this

There is no way to call another bot, forward variables and map them into different variables in called bot? Something like functions with parameters which are then used in another parameters inside the function

**Comment by altomarketing** [comment] 2022-11-07 22:25
> Variable values should be shared across typebots.
> 
> If you create a variable "Score" on typebot A **and** typebot B, if they are linked together they should share this variable value

so, if i have several bots all with same variables names, i can move between them and variables always will be prepopulated ?

**Comment by baptisteArno** [comment] 2022-11-08 08:19
In theory, yes 👍

**Comment by baptisteArno** [comment] 2022-12-20 10:27
I'll close this for now because I don't have a way to reproduce this consistently. Feel free to re-open! 👍

**Closed by baptisteArno** 2022-12-20 10:27 UTC
Labels: Bug 🐛
