### ISSUE TITLE
Docker self hosting build of viewer failed. Error occurred prerendering page "/404"

### ISSUE THREAD

**Issue by samsonmolou** [baptisteArno/typebot.io#9] opened 2022-03-29 12:51 UTC
I have followed the steps for the [Local Setup](https://github.com/baptisteArno/typebot.io#local-setup) but the viewer compilation fails during the prerendering page "/404" in nextjs build. 

The database inspector at http://localhost:5555/ works fine but the builder at http://localhost:3000/ only displays a compilation error message.

Here are the relevant lines from the terminal build command:
```
#21 28.01 viewer:build: $ next build
#21 28.41 viewer:build: info  - Loaded env from /app/apps/viewer/.env.production
#21 28.62 viewer:build: warn  - You have enabled experimental feature(s).
#21 28.62 viewer:build: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
#21 28.62 viewer:build:
#21 28.64 viewer:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
#21 28.64 viewer:build: This information is used to shape Next.js' roadmap and prioritize features.
#21 28.64 viewer:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#21 28.64 viewer:build: https://nextjs.org/telemetry
#21 28.64 viewer:build:
#21 28.69 viewer:build: info  - Checking validity of types...
#21 34.23 viewer:build: info  - Creating an optimized production build...
#21 44.38 viewer:build: info  - Compiled successfully
#21 44.38 viewer:build: info  - Collecting page data...
#21 46.47 viewer:build: info  - Generating static pages (0/1)
#21 46.60 viewer:build:
#21 46.60 viewer:build: Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
#21 46.60 viewer:build: Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
#21 46.60 viewer:build:     at S (/app/apps/viewer/node_modules/react/cjs/react.production.min.js:18:327)
#21 46.60 viewer:build:     at Object.exports.useContext (/app/apps/viewer/node_modules/react/cjs/react.production.min.js:22:269)
#21 46.60 viewer:build:     at Html (/app/apps/viewer/.next/server/pages/_document.js:538:73)
#21 46.60 viewer:build:     at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
#21 46.60 viewer:build:     at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
#21 46.60 viewer:build:     at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
#21 46.60 viewer:build:     at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
#21 46.60 viewer:build:     at Object.exports.renderToStaticMarkup (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
#21 46.60 viewer:build:     at renderToHTML (/app/node_modules/next/dist/server/render.js:909:39)
#21 46.60 viewer:build:     at async /app/node_modules/next/dist/export/worker.js:269:36
#21 46.60 viewer:build: info  - Generating static pages (1/1)
#21 46.60 viewer:build:
#21 46.60 viewer:build: > Build error occurred
#21 46.60 viewer:build: Error: Export encountered errors on following paths:
#21 46.60 viewer:build:         /404
#21 46.60 viewer:build:     at /app/node_modules/next/dist/export/index.js:498:19
#21 46.60 viewer:build:     at runMicrotasks (<anonymous>)
#21 46.60 viewer:build:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#21 46.60 viewer:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:75:20)
#21 46.60 viewer:build:     at async /app/node_modules/next/dist/build/index.js:1024:17
#21 46.60 viewer:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:75:20)
#21 46.60 viewer:build:     at async /app/node_modules/next/dist/build/index.js:898:13
#21 46.60 viewer:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:75:20)
#21 46.60 viewer:build:     at async Object.build [as default] (/app/node_modules/next/dist/build/index.js:82:25)
#21 46.66 viewer:build: error Command failed with exit code 1.
#21 46.66 viewer:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#21 46.67 viewer:build: Error: command finished with error: command (apps/viewer) yarn run build exited (1)
#21 46.67 command (apps/viewer) yarn run build exited (1)
#21 46.67
#21 46.67  Tasks:    4 successful, 5 total
#21 46.67 Cached:    0 cached, 5 total
#21 46.67   Time:    46s
#21 46.67
#21 46.69 error Command failed with exit code 1.
#21 46.69 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn turbo run build --scope=${SCOPE} --include-dependencies]: exit code: 1
```

**Comment by baptisteArno** [comment] 2022-03-29 13:02
It happens with the `yarn dev` command?

I had this error message once. Try to delete your `node_modules` in root directory, delete `.next` folders in both `builder` and `viewer` folders and then you can run again:

```sh
yarn && yarn dev
```

**Comment by samsonmolou** [comment] 2022-03-29 13:34
It happens when i run `docker-compose up` after i cloned the repo from GitHub.
There is no 'node_modules', `.next` folder in the root directory.

**Comment by baptisteArno** [comment] 2022-03-29 13:38
I don't understand, are you following [Local Setup](https://github.com/baptisteArno/typebot.io#local-setup) instructions? You never have to run `docker-compose up`

**Comment by samsonmolou** [comment] 2022-03-29 13:58
Sorry mate... I was following the self hosting guide [here](https://docs.typebot.io/self-hosting/docker)

Thanks.

**Comment by baptisteArno** [comment] 2022-03-29 15:54
> It happens when i run `docker-compose up` after i cloned the repo from GitHub. There is no `node_modules`, `.next` folder in the root directory.

Is there a .next folder in the `viewer` directory though?

Can you try to rebuild it? Does it happen consistently?

**Comment by samsonmolou** [comment] 2022-03-29 16:08
Yes, there is a hidden `.next` folder in the `viewer` directory

I had just tried to rebuild it. The same error happens again. I can say it is consistent.
Find the command line result [here](https://github.com/baptisteArno/typebot.io/files/8373193/typebot.txt)

**Comment by baptisteArno** [comment] 2022-03-29 16:20
> Yes, there is a hidden .next folder in the viewer directory

Have you deleted it? 😆

Make sure to delete every `node_modules` and `.next` folders you can find in the project and try again

**Comment by samsonmolou** [comment] 2022-03-29 18:21
> Have you deleted it? 😆

Yes, both folder in viewer and builder directory before running `docker-compose up`

**Comment by baptisteArno** [comment] 2022-03-29 19:41
That's odd! Can you try:

```sh
docker-compose build --no-cache
```

**Comment by samsonmolou** [comment] 2022-03-29 19:54
yeah really odd.

Same thing again with `docker-compose build --no-cache`

**Comment by samsonmolou** [comment] 2022-03-29 20:54
I think the solution to fix this error is referenced here [Prerender Error](https://nextjs.org/docs/messages/prerender-error)

> [Why This Error Occurred](https://nextjs.org/docs/messages/prerender-error#why-this-error-occurred)
While prerendering a page an error occurred. This can occur for many reasons from adding non-pages e.g. components to your pages folder or expecting props to be populated which are not.
[Possible Ways to Fix It](https://nextjs.org/docs/messages/prerender-error#possible-ways-to-fix-it)
Make sure to move any non-pages out of the pages folder
Check for any code that assumes a prop is available, even when it might not be
Set default values for all dynamic pages' props (avoid undefined, use null instead so it can be serialized)
Check for any out of date modules that you might be relying on
Make sure your component handles fallback if it is enabled in getStaticPaths. [Fallback docs](https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-false)
Make sure you are not trying to export (next export) pages that have server-side rendering enabled [(getServerSideProps)](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)

**Comment by baptisteArno** [comment] 2022-03-30 05:06
This is the related issue: https://github.com/vercel/next.js/discussions/13439

I'll investigate further but I've already tried on 3 different machines, I can't reproduce.

What's your operating system ?

**Comment by baptisteArno** [comment] 2022-03-30 05:56
I've just pushed a potential fix, can you pull the `main` branch, making sure your Dockerfile has this line:

`RUN yarn turbo run build --scope=${SCOPE} --include-dependencies --no-deps`

And try again without cache?

**Comment by samsonmolou** [comment] 2022-03-30 08:11
I'm using Windows 11 with WSL installed and Docker Desktop.
 I don't no why bu the error keep occurring.

```
typebot.io git:(main) ✗ docker-compose up
[+] Running 14/14
 ⠿ db Pulled                                                                                                      39.8s
   ⠿ c229119241af Pull complete                                                                                   10.4s
   ⠿ 3ff4ca332580 Pull complete                                                                                   10.7s
   ⠿ 5037f3c12de6 Pull complete                                                                                   10.8s
   ⠿ 0444ef779945 Pull complete                                                                                   10.9s
   ⠿ 47098a4166e7 Pull complete                                                                                   11.3s
   ⠿ 203cca980fab Pull complete                                                                                   11.4s
   ⠿ a479b6c0e001 Pull complete                                                                                   11.5s
   ⠿ 1eaa9abe8ca4 Pull complete                                                                                   11.6s
   ⠿ 113f50383ee6 Pull complete                                                                                   28.6s
   ⠿ 2abdc4f6d216 Pull complete                                                                                   28.7s
   ⠿ 208ab7ebe2d3 Pull complete                                                                                   28.8s
   ⠿ 0695aa3abf50 Pull complete                                                                                   29.0s
   ⠿ ba6456490b54 Pull complete                                                                                   29.0s
[+] Building 65.4s (34/48)
 => [typebotio_builder internal] load build definition from Dockerfile                                             0.1s
 => => transferring dockerfile: 1.25kB                                                                             0.0s
 => [typebotio_builder internal] load .dockerignore                                                                0.2s
 => => transferring context: 112B                                                                                  0.0s
 => [typebotio_viewer internal] load build definition from Dockerfile                                              0.2s
 => => transferring dockerfile: 1.25kB                                                                             0.1s
 => [typebotio_viewer internal] load .dockerignore                                                                 0.3s
 => => transferring context: 34B                                                                                   0.0s
 => [typebotio_builder internal] load metadata for docker.io/library/node:16-slim                                  8.6s
 => [typebotio_builder internal] load build context                                                                0.4s
 => => transferring context: 23.61MB                                                                               0.3s
 => [typebotio_builder base 1/2] FROM docker.io/library/node:16-slim@sha256:380112b3f3df96ae593b0b89f4c44e501e9ae  0.0s
 => => resolve docker.io/library/node:16-slim@sha256:380112b3f3df96ae593b0b89f4c44e501e9ae0ec1580b270b50f8ac52688  0.0s
 => [typebotio_viewer internal] load build context                                                                 0.1s
 => => transferring context: 351.89kB                                                                              0.1s
 => CACHED [typebotio_builder base 2/2] WORKDIR /app                                                               0.0s
 => CACHED [typebotio_viewer pruner 1/3] RUN yarn global add turbo@1.1.5                                           0.0s
 => [typebotio_viewer pruner 2/3] COPY . .                                                                         3.2s
 => CACHED [typebotio_builder pruner 1/3] RUN yarn global add turbo@1.1.5                                          0.0s
 => [typebotio_builder pruner 2/3] COPY . .                                                                        2.9s
 => [typebotio_builder pruner 3/3] RUN turbo prune --scope=builder --docker                                        1.1s
 => [typebotio_viewer pruner 3/3] RUN turbo prune --scope=viewer --docker                                          1.0s
 => CACHED [typebotio_viewer installer 1/3] COPY --from=pruner /app/out/json/ .                                    0.0s
 => CACHED [typebotio_viewer installer 2/3] COPY --from=pruner /app/out/yarn.lock ./yarn.lock                      0.0s
 => CACHED [typebotio_viewer installer 3/3] RUN yarn install --frozen-lockfile                                     0.0s
 => CACHED [typebotio_viewer builder 1/5] COPY --from=installer /app/ .                                            0.0s
 => CACHED [typebotio_viewer builder 2/5] COPY --from=pruner /app/out/full/ .                                      0.0s
 => CACHED [typebotio_viewer builder 3/5] RUN apt-get -qy update && apt-get -qy install openssl                    0.0s
 => ERROR [typebotio_viewer builder 4/5] RUN yarn turbo run build --scope=viewer --include-dependencies --no-dep  51.8s
 => CACHED [typebotio_builder installer 1/3] COPY --from=pruner /app/out/json/ .                                   0.0s
 => CACHED [typebotio_builder installer 2/3] COPY --from=pruner /app/out/yarn.lock ./yarn.lock                     0.0s
 => CACHED [typebotio_builder installer 3/3] RUN yarn install --frozen-lockfile                                    0.0s
 => CACHED [typebotio_builder builder 1/5] COPY --from=installer /app/ .                                           0.0s
 => CACHED [typebotio_builder builder 2/5] COPY --from=pruner /app/out/full/ .                                     0.0s
 => CACHED [typebotio_builder builder 3/5] RUN apt-get -qy update && apt-get -qy install openssl                   0.0s
 => CANCELED [typebotio_builder builder 4/5] RUN yarn turbo run build --scope=builder --include-dependencies --n  52.0s
 => CACHED [typebotio_builder runner 1/9] WORKDIR /app                                                             0.0s
 => CACHED [typebotio_viewer runner 2/9] COPY ./packages/db/prisma ./prisma                                        0.0s
 => CACHED [typebotio_viewer runner 3/9] COPY --from=installer /app/node_modules ./node_modules                    0.0s
 => CACHED [typebotio_builder runner 2/9] COPY ./packages/db/prisma ./prisma                                       0.0s
 => CACHED [typebotio_builder runner 3/9] COPY --from=installer /app/node_modules ./node_modules                   0.0s
------
 > [typebotio_viewer builder 4/5] RUN yarn turbo run build --scope=viewer --include-dependencies --no-deps:
#41 0.884 yarn run v1.22.18
#41 0.908 $ /app/node_modules/.bin/turbo run build --scope=viewer --include-dependencies --no-deps
#41 1.119  WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
#41 1.119 • Packages in scope: bot-engine, db, models, utils, viewer
#41 1.119 • Running build in 5 packages
#41 1.120 db:build: cache miss, executing 71439b46cefe48d1
#41 1.258 db:build: $ yarn generate:schema
#41 1.404 db:build: $ dotenv -e ../../apps/builder/.env.local prisma generate
#41 1.946 db:build: Prisma schema loaded from prisma/schema.prisma
#41 8.961 db:build:
#41 8.961 db:build: ✔ Generated Prisma Client (3.10.0 | library) to ./../../node_modules/@prisma/client in 328ms
#41 8.961 db:build: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
#41 8.961 db:build: ```
#41 8.961 db:build: import { PrismaClient } from '@prisma/client'
#41 8.961 db:build: const prisma = new PrismaClient()
#41 8.961 db:build: ```
#41 9.733 models:build: cache miss, executing 9e238d44f362d437
#41 9.897 models:build: $ tsc
#41 11.88 utils:build: cache miss, executing c7a717be39db19b7
#41 12.02 utils:build: $ yarn rollup -c
#41 12.21 utils:build: $ /app/node_modules/.bin/rollup -c
#41 12.67 utils:build:
#41 12.67 utils:build: src/index.ts → dist/cjs/index.js, dist/esm/index.js...
#41 15.05 utils:build: created dist/cjs/index.js, dist/esm/index.js in 2.3s
#41 15.05 utils:build:
#41 15.05 utils:build: dist/esm/types/index.d.ts → dist/index.d.ts...
#41 15.09 utils:build: created dist/index.d.ts in 43ms
#41 15.14 bot-engine:build: cache miss, executing ccb0d9c4fb001b47
#41 15.28 bot-engine:build: $ yarn rollup -c
#41 15.42 bot-engine:build: $ /app/node_modules/.bin/rollup -c
#41 15.88 bot-engine:build:
#41 15.88 bot-engine:build: src/index.ts → dist/cjs/index.js, dist/esm/index.js...
#41 30.99 bot-engine:build: created dist/cjs/index.js, dist/esm/index.js in 15.1s
#41 30.99 bot-engine:build:
#41 30.99 bot-engine:build: dist/esm/types/src/index.d.ts → dist/index.d.ts...
#41 31.01 bot-engine:build: (!) Unresolved dependencies
#41 31.01 bot-engine:build: https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
#41 31.01 bot-engine:build: util (imported by dist/esm/types/src/index.d.ts)
#41 31.01 bot-engine:build: created dist/index.d.ts in 23ms
#41 31.08 viewer:build: cache miss, executing cd50cc9f10edc459
#41 31.22 viewer:build: $ next build
#41 31.72 viewer:build: info  - Loaded env from /app/apps/viewer/.env.production
#41 32.09 viewer:build: warn  - You have enabled experimental feature(s).
#41 32.09 viewer:build: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
#41 32.09 viewer:build:
#41 32.11 viewer:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
#41 32.11 viewer:build: This information is used to shape Next.js' roadmap and prioritize features.
#41 32.11 viewer:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#41 32.11 viewer:build: https://nextjs.org/telemetry
#41 32.11 viewer:build:
#41 32.16 viewer:build: info  - Checking validity of types...
#41 38.53 viewer:build: info  - Creating an optimized production build...
#41 48.73 viewer:build: info  - Compiled successfully
#41 48.73 viewer:build: info  - Collecting page data...
#41 50.85 viewer:build: info  - Generating static pages (0/1)
#41 50.99 viewer:build:
#41 50.99 viewer:build: Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
#41 50.99 viewer:build: Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
#41 50.99 viewer:build:     at S (/app/apps/viewer/node_modules/react/cjs/react.production.min.js:18:327)
#41 50.99 viewer:build:     at Object.exports.useContext (/app/apps/viewer/node_modules/react/cjs/react.production.min.js:22:269)
#41 50.99 viewer:build:     at Html (/app/apps/viewer/.next/server/pages/_document.js:538:73)
#41 50.99 viewer:build:     at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
#41 50.99 viewer:build:     at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
#41 50.99 viewer:build:     at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
#41 50.99 viewer:build:     at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
#41 50.99 viewer:build:     at Object.exports.renderToStaticMarkup (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
#41 50.99 viewer:build:     at renderToHTML (/app/node_modules/next/dist/server/render.js:909:39)
#41 50.99 viewer:build:     at async /app/node_modules/next/dist/export/worker.js:269:36
#41 50.99 viewer:build: info  - Generating static pages (1/1)
#41 50.99 viewer:build:
#41 50.99 viewer:build: > Build error occurred
#41 50.99 viewer:build: Error: Export encountered errors on following paths:
#41 50.99 viewer:build:         /404
#41 50.99 viewer:build:     at /app/node_modules/next/dist/export/index.js:498:19
#41 50.99 viewer:build:     at runMicrotasks (<anonymous>)
#41 50.99 viewer:build:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#41 50.99 viewer:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:75:20)
#41 50.99 viewer:build:     at async /app/node_modules/next/dist/build/index.js:1024:17
#41 50.99 viewer:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:75:20)
#41 50.99 viewer:build:     at async /app/node_modules/next/dist/build/index.js:898:13
#41 50.99 viewer:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:75:20)
#41 50.99 viewer:build:     at async Object.build [as default] (/app/node_modules/next/dist/build/index.js:82:25)
#41 51.04 viewer:build: error Command failed with exit code 1.
#41 51.04 viewer:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#41 51.05 viewer:build: Error: command finished with error: command (apps/viewer) yarn run build exited (1)
#41 51.05 command (apps/viewer) yarn run build exited (1)
#41 51.05
#41 51.05  Tasks:    4 successful, 5 total
#41 51.05 Cached:    0 cached, 5 total
#41 51.05   Time:    50.068s
#41 51.05
#41 51.06 error Command failed with exit code 1.
#41 51.06 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn turbo run build --scope=${SCOPE} --include-dependencies --no-deps]: exit code: 1
```

**Comment by baptisteArno** [comment] 2022-03-31 12:14
What I suggest is to:

1. Clone the repo in a new location so that you are sure you're on a fresh base
2. Copy-paste `env.production.example` files
3. Run `docker-compose build --no-cache`

**Comment by baptisteArno** [comment] 2022-04-04 08:10
I've stumbled upon this issue this WE and pushed a fix. 👍

**Closed by baptisteArno** 2022-04-04 08:10 UTC

**Comment by samsonmolou** [comment] 2022-04-04 15:00
Thanks
