### ISSUE TITLE
Feature Request: Timeout for text input

### ISSUE THREAD

**Issue by unilogica** [baptisteArno/typebot.io#1291] opened 2024-02-26 18:43 UTC
I really wish there was a way to apply a timeout to text capture. And after the defined time limit, if the user did not respond he could simply apply null as a response.

Practical example: if after 2 minutes a user doesn't respond to an input text, I would send a message like: "Hey, are you still there?"

In practice, if the user doesn't respond at all, I can't move forward in the automation flow and it will stop. After the timeout I would like to send a webhook with the transcription of the conversation by email to the user.

But if there is any way around this and someone can help me, I'm out of ideas of what to test.

**Comment by baptisteArno** [comment] 2024-02-28 14:41
Duplicate of #1225

**Closed by baptisteArno** 2024-02-28 14:41 UTC
