### ISSUE TITLE
[Bug] http request not send body 

### ISSUE THREAD

**Issue by mtuliosan** [baptisteArno/typebot.io#1643] opened 2024-07-16 03:21 UTC
I am experiencing an issue with Typebot where it is not sending the values in the body of the request. When I restart the container, it works for a while but then stops sending the values again. There are no error logs, and the Typebot logs show that the request was sent correctly for my specific test and an integration with Baserow. Sending a test request works perfectly, but when I test the flow, it stops sending the values.

I initially thought the issue might be with Baserow, but the same request works fine in Postman. I also considered that the variables might be losing their values, but even with fixed values in the body, it does not work. When I enable the "execute on client" flag, it works, but when testing via WhatsApp using the Evolution API, the flow stops. With this flag active, the JSON is sent normally on the web.

**Comment by baptisteArno** [comment] 2024-07-16 14:01
Can you clearly describe it by following this template:

1. Steps to reproduce
2. What's happening
3. What were you expecting

It's even better if you can provide a screen recording.

**Comment by mtuliosan** [comment] 2024-07-16 15:11
[Uploading Gravação de tela de 16-07-2024 12:01:56.webm…]()

**Comment by mtuliosan** [comment] 2024-07-16 15:13
Steps to reproduce
[Uploading Gravação de tela de 16-07-2024 12:01:56.webm…]()

What's happening
Not send body in request http POST

What were you expecting
send body in request http POST

**Comment by Deyvi-dev** [comment] 2024-07-16 23:10
@baptisteArno @mtuliosan  I'm having the same problem myself
in the typebot itself from https://app.typebot.io
I believe it is something with the Serverless or Edge function in vercel

**Comment by baptisteArno** [comment] 2024-07-17 13:00
Can you reproduce the bug by consuming webhook.site URL? AFAIK, the error can come from Baserow

**Comment by eltonciatto** [comment] 2024-07-17 14:58
I'm also facing this error on my self-hosting typebot, in fact, I was going to report it to you before finding this issue, my dev and I discovered, in part, what is causing the problem... We did tests on self-hosting on others servers outside of Vercel, and HTTP 
Request worked perfectly, however, when it is used in Vercel, both in your version and in mine, it generates this error.  (i.e. we have concluded that this is a unique issue using Vercel).  We are migrating to Railway and it solved the problem.  We looked at everything related to Vercel and didn't consider what it could be.

_Translate using Google Translate_

**Comment by mtuliosan** [comment] 2024-07-17 15:31
Indeed, I tested it with webhook.site and Baserow, and the body is only not being sent to Baserow. Strangely, when testing from Typebot, it works, but it doesn't work when running the flow. When I restart Typebot, it starts working again. I never have to change anything on Baserow.

**Comment by mtuliosan** [comment] 2024-07-17 17:01
Indeed, I tested it via Postman with Baserow and it works normally. The problem only occurs with Typebot. Strangely, when testing from Typebot, it works, but it doesn't work when running the flow. When I restart Typebot, it starts working again. I never have to change anything on Baserow.

@baptisteArno

**Comment by mtuliosan** [comment] 2024-07-18 03:19
Steps to reproduce:

![Captura de tela de 2024-07-18 00-12-13](https://github.com/user-attachments/assets/781ff47c-5baf-44be-9399-7cfcfbb44a75)

![Captura de tela de 2024-07-18 00-12-31](https://github.com/user-attachments/assets/e2291293-f66d-41ba-9ed7-5e4b7452d855)

Example:
https://app.typebot.io/typebots/clyqokouw0027jql9vp8h361m/edit

**Comment by baptisteArno** [comment] 2024-07-18 14:21
Can't reproduce so I'll need another example for someone else maybe to guess what's wrong

**Comment by eltonciatto** [comment] 2024-07-18 14:42
We were able to reproduce the error only with typebot on Vercel, using Baserow to save data in the database, it does not save and gives an error in the HTTP Request only in the POST method

**Comment by baptisteArno** [comment] 2024-07-18 14:42
So the issue arises only with Baserow? 😂

**Comment by eltonciatto** [comment] 2024-07-18 14:43
No, with others served too!  I used Baserow as an example.

**Comment by baptisteArno** [comment] 2024-07-18 14:45
I just tried with webhook.site, it works just fine so I am confused. Can you provide an easily reproducable example?

**Comment by eltonciatto** [comment] 2024-07-18 14:56
![IMG-20240715-WA0016.jpg](https://github.com/user-attachments/assets/112424a2-a7f2-4dc2-bd5d-7159d8f66871)

![IMG-20240712-WA0002(2).jpg](https://github.com/user-attachments/assets/4ce74ddd-5e74-41f3-8f06-8d38c87762cc)




The testing we did was both on Baserow and on the Make API.

See images above.

Note: I don't know in which service the user who opened the issue is facing a problem, however, in my tests, there was a problem in both Make and Baserow.

**Comment by mtuliosan** [comment] 2024-07-18 16:45
But in your case, you need to add the header Content-Type application/json.

**Comment by N0N4M3BNS** [comment] 2024-07-28 18:31
My side has a problem too, when using the POST method, my body is not passing. So how do I debug and fix it?

**Comment by N0N4M3BNS** [comment] 2024-07-30 02:01
![image](https://github.com/user-attachments/assets/3b02045e-4a6a-4ed9-a2e6-76a4b2b2bf99)
Block HTTP Request, for header in POST method like have problem, when pass content-type application/json not detect, when pass x-api-key not work too. Someone can answer this issues?

**Comment by renesamajauskas** [comment] 2024-08-06 22:29
Hello everyone.. I'm new here!

I've been having the same problem for some time now.
Today in some tests I realized that this happens after a request is made to OpenAI (in my case).

When I take down the typebot container and start it again, it works again (until there is another request to OpenAI, which causes blank lines to be created in Baserow again)

The last version that worked normally here was **2.24.1**... After that, all updates had this same problem

I didn't notice any changes in the logs, either from typebot or baserow...

The request works normally, bringing result 200, but the data is not passed, as people commented

**Comment by baptisteArno** [comment] 2024-11-12 15:47
Closing. Feel free to re-open if you have more info

**Closed by baptisteArno** 2024-11-12 15:47 UTC
