### ISSUE TITLE
The string did not match the expected pattern.

### ISSUE THREAD

**Issue by j-dogcoder** [baptisteArno/typebot.io#270] opened 2023-01-24 04:17 UTC
When using a webhook, I get the error `The string did not match the expected pattern.` Unsure as to what is wrong here...

**Comment by baptisteArno** [comment] 2023-01-24 07:03
Where do you get this error?

Is there any issue? Because, it can also just be an informational message.

**Comment by j-dogcoder** [comment] 2023-01-24 13:54
It also continues to try the request... it it waiting for a response from the webhook?

**Comment by j-dogcoder** [comment] 2023-01-24 23:05
Thoughts on this @baptisteArno?

**Comment by baptisteArno** [comment] 2023-01-25 07:31
Can you provide a way for me reproduce the issue?

**Comment by baptisteArno** [comment] 2023-02-06 06:52
Will close this. Feel free to re-open if you have a minimalist reproduction 🙏

**Closed by baptisteArno** 2023-02-06 06:52 UTC
