### ISSUE TITLE
An error occurred while loading the bot.  Input validation failed

### ISSUE THREAD

**Issue by alissonryan** [baptisteArno/typebot.io#762] opened 2023-09-05 00:57 UTC
I'm encountering a bug in the latest version of typebot 2.16

whenever I put a box to capture email I get this message in my preview:
An error occurred while loading the bot.
input validation failed

I deleted the email box and replaced it with text and it worked, but I connected a bubble with another bubble that was already in the flow and it gave this error again. Here's the screen print of how the connections are.
<img width="1439" alt="Screenshot 2023-09-04 at 21 56 49" src="https://github.com/baptisteArno/typebot.io/assets/40619781/8a3fb950-5cc9-4ded-a605-cc675b83c2a1">

I'm using docker compose as installation

**Comment by alissonryan** [comment] 2023-09-05 01:09
I think it's when I put the button input it generates this error.

**Comment by baptisteArno** [comment] 2023-09-05 06:41
The latest version is v2.17. Can you upgrade?

**Comment by alissonryan** [comment] 2023-09-05 10:16
I haven't updated yet, I'm using 2.16

actually, I'm using another docker image because your original one doesn't work for ARM servers and I found another one from Elestio which is for this type.

**Comment by baptisteArno** [comment] 2023-09-06 06:11
Ok.

Can you share what's the error message on the server side? (`docker-compose logs`)

**Comment by alissonryan** [comment] 2023-09-06 14:56
yes, I create via direct scratch. And I noticed that the error occurs when I insert the text and buttons inputs.

when I take these 2 inputs I can have a preview of the chat and publish.

I tried using a template and editing it, but even so when I edit the template it generates this error. Already the template without being edited I can have a preview with the buttons and text in it.

Could it be something related to Elestio's image? I already went to their discord channel to request an update.

What error do you need to log? there is a lot of access information in this log.

**Comment by baptisteArno** [comment] 2023-09-07 06:29
Can you invite me on that bot so that I can debug what's wrong? baptiste@typebot.io

**Comment by alissonryan** [comment] 2023-09-07 13:24
ok, invitation sent. I would suggest creating a bot from scratch putting the button and text inputs and trying to see the preview.

**Comment by baptisteArno** [comment] 2023-09-07 13:43
I can't reproduce, can you give me the exact procedure to reproduce?

**Comment by baptisteArno** [comment] 2023-09-07 13:51
In the mean time, you can upgrade to the official typebot image that supports arm now. There's a good chance it will fix the issue.

(v2.17.2)

**Comment by alissonryan** [comment] 2023-09-07 15:26
> I can't reproduce, can you give me the exact procedure to reproduce?

Every time I create a typebot from scratch, I put the text and then I put the button or text input for the user to choose or write text, the preview doesn't load and generates this error in the screen print above.

> In the mean time, you can upgrade to the official typebot image that supports arm now. There's a good chance it will fix the issue.
> 
> (v2.17.2)

can i replace the image of the Elestio for the official version? the problem that I will have to backup all the typebot's created, right?

**Comment by alissonryan** [comment] 2023-09-07 16:13
I saw your test typebot there, and I inserted an extra button and it gave this error

![Screenshot 2023-09-07 at 13 12 26](https://github.com/baptisteArno/typebot.io/assets/40619781/970c5abc-4ef2-40a2-846e-86687f7533b6)

**Comment by alissonryan** [comment] 2023-09-07 22:37
I changed the image to yours just by changing docker-compose.yml and now I'm having an error when starting the chat, I can't see anything as shown in the print below.

<img width="490" alt="Screenshot 2023-09-07 at 19 37 08" src="https://github.com/baptisteArno/typebot.io/assets/40619781/2c2b7cce-5731-4654-b909-5f5f411560dd">

**Comment by baptisteArno** [comment] 2023-09-08 10:38
There is probably a environment variable missing. Make sure to have all the required env var in the viewer environment: https://docs.typebot.io/self-hosting/configuration

You can see the error in the server logs: `docker-compose logs`

**Comment by alissonryan** [comment] 2023-09-08 11:05
all variables are already configured, even Google, Unsplash and Giphy


docker-compose logs

> typebotio-typebot-viewer-1  | env.sh loaded
typebotio-typebot-viewer-1  | Matched inline env:
typebotio-typebot-viewer-1  | NEXT_PUBLIC_SMTP_FROM=contato@alissonryan.com.br
typebotio-typebot-viewer-1  | NEXT_PUBLIC_VIEWER_URL=https://chat.alissonryan.com.br
typebotio-typebot-viewer-1  | Reading ./apps/viewer/.env.production...
typebotio-typebot-viewer-1  | NEXT_PUBLIC_VIEWER_URL=
typebotio-typebot-viewer-1  | NEXT_PUBLIC_E2E_TEST=
typebotio-typebot-viewer-1  | NEXT_PUBLIC_SMTP_FROM=contato@alissonryan.com.br
typebotio-typebot-viewer-1  | NEXT_PUBLIC_VIEWER_URL=https://chat.alissonryan.com.br
typebotio-typebot-viewer-1  | Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
typebotio-typebot-viewer-1  | Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
typebotio-typebot-viewer-1  | env.sh done
typebotio-typebot-viewer-1  | 
typebotio-typebot-viewer-1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebotio-typebot-viewer-1  | 
typebotio-typebot-viewer-1  | ✔ Generated Prisma Client (5.0.0 | library) to ./node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client in 733ms
typebotio-typebot-viewer-1  | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebotio-typebot-viewer-1  | ```
typebotio-typebot-viewer-1  | import { PrismaClient } from '@prisma/client'
typebotio-typebot-viewer-1  | const prisma = new PrismaClient()
typebotio-typebot-viewer-1  | ```
typebotio-typebot-viewer-1  | - info Loaded env from /app/apps/viewer/.env.production
typebotio-typebot-viewer-1  | Listening on port 3000 url: http://c054a16cc0d8:3000
typebotio-typebot-viewer-1  | - info Loaded env from /app/apps/viewer/.env.production
typebotio-typebot-viewer-1  | (node:96) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
typebotio-typebot-viewer-1  | 
typebotio-typebot-viewer-1  | Please migrate your code to use AWS SDK for JavaScript (v3).
typebotio-typebot-viewer-1  | For more information, check the migration guide at https://a.co/7PzMCcy
typebotio-typebot-viewer-1  | (Use `node --trace-warnings ...` to show where the warning was created)

> typebotio-typebot-builder-1  | - event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
typebotio-typebot-builder-1  | - ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/builder/public/__ENV.js'.
typebotio-typebot-builder-1  | wait-for-it.sh: waiting 60 seconds for db.kabaojdbydoydrfsduau.supabase.co:5432
typebotio-typebot-builder-1  | wait-for-it.sh: db.kabaojdbydoydrfsduau.supabase.co:5432 is available after 0 seconds
typebotio-typebot-builder-1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebotio-typebot-builder-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "db.kabaojdbydoydrfsduau.supabase.co:5432"
typebotio-typebot-builder-1  | 
typebotio-typebot-builder-1  | 55 migrations found in prisma/migrations
typebotio-typebot-builder-1  | 
typebotio-typebot-builder-1  | 
typebotio-typebot-builder-1  | No pending migrations to apply.
typebotio-typebot-builder-1  | Listening on port 3000 url: http://f804944af8eb:3000
typebotio-typebot-builder-1  | Archiving 100 / 2 results...

> typebotio-createbuckets-1    | Added `minio` successfully.
typebotio-createbuckets-1    | mc: <ERROR> Unable to make bucket `minio/typebot`. Your previous request to create the named bucket succeeded and you already own it.
typebotio-createbuckets-1    | Access permission for `minio/typebot/public` is set to `public`

**Comment by baptisteArno** [comment] 2023-09-08 12:27
Do you have NEXTAUTH_URL set on the viewer container?

**Comment by alissonryan** [comment] 2023-09-08 12:31
> Do you have NEXTAUTH_URL set on the viewer container?

this NEXTAUTH_URL is only in the builder's container, do I need to put it in the viewer too?

**Comment by baptisteArno** [comment] 2023-09-08 12:34
Yes, see https://github.com/baptisteArno/typebot.io/releases/tag/v2.17.0

**Comment by alissonryan** [comment] 2023-09-08 12:35
> Yes, see https://github.com/baptisteArno/typebot.io/releases/tag/v2.17.0

is it the same URL as the builder container?

**Comment by baptisteArno** [comment] 2023-09-08 12:43
Exactly, yes!

**Comment by baptisteArno** [comment] 2023-09-08 12:43
The "Input validation failed" issue is fixed on version 2.17 👍

**Closed by baptisteArno** 2023-09-08 12:43 UTC

**Comment by alissonryan** [comment] 2023-09-08 12:45
I will change the URL and change the image to its original and do the test. I'll be right back to edit this message and let you know if it worked.
