### ISSUE TITLE
AI Assistant field not populating

### ISSUE THREAD

**Issue by CptPlastic** [baptisteArno/typebot.io#1771] opened 2024-09-05 16:54 UTC
**Describe the bug**
Field just says loading 

**To Reproduce**
1. Go to Any AI BLOCK
2. Click on Assistant ID
3. See error

**Expected behavior**
Should see a list of models

**Workaround**
Set env variable to model of your choice then select it for assistant field.

![image](https://github.com/user-attachments/assets/fe587f88-55cb-4570-9b3f-69f8d534417f)

Element
`<input type="text" autocomplete="off" class="chakra-input select-input css-tt29ne" placeholder="Loading..." id="field-:reg:" disabled="" value="">`

**Comment by richieri-bps** [comment] 2024-09-06 12:20
It's happening to me as well after I updated my typebot instance yesterday. In my case, I'm trying to pick an assistant

![image](https://github.com/user-attachments/assets/1fbe92ae-beec-4d6f-bbd7-0faa91e16990)

**Comment by richieri-bps** [comment] 2024-09-06 12:48
I downgraded the build to version 2.27 and the problem is gone. Seems like a 2.28 issue

**Comment by baptisteArno** [comment] 2024-09-06 13:59
Sorry guys. You can upgrade to 2.28.2, it should be fixed!

**Closed by baptisteArno** 2024-09-06 13:59 UTC
