### ISSUE TITLE
Unexpected token 'I', "Internal S"... is not valid JSON

### ISSUE THREAD

**Issue by itzomen** [baptisteArno/typebot.io#235] opened 2023-01-11 21:04 UTC
Hello, I get this error as shown below, in the console when trying to view a typebot or to perform an action:
```
Unexpected token 'I', "Internal S"... is not valid JSON
```
Very similar to issue #178 

I'm using version `2.9.1` and faced the same issue as #44 before this one arose.

Additionally, I get `https://undefined/typebot-bloggers-p7dtme8` in the share link though I have crosschecked my envs configuration and checked the issue #180 and #106

Configs as follows:
```env
# Viewer
ENCRYPTION_SECRET=abc
NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
DATABASE_URL=postgresql://type:bot@localhost:5432/typebot
NEXTAUTH_URL=https://builder.example.com

SMTP_USERNAME=username
SMTP_PASSWORD=pass123
SMTP_HOST=smtp.host
SMTP_PORT=587
NEXT_PUBLIC_SMTP_FROM=Notifications <notifications@example.com>
SMTP_SECURE=false
SMTP_AUTH_DISABLED=false

S3_ACCESS_KEY=4566
S3_SECRET_KEY=ghuu
S3_BUCKET=tyre
#S3_PORT=9000
S3_ENDPOINT=fra1.digitaloceanspaces.com
S3_SSL=true
```
```env
# Builder
ADMIN_EMAIL=hello@example.com
DATABASE_URL=postgresql://type:bot@localhost:5432/typebot
ENCRYPTION_SECRET=!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+Mb #256-bits secret (can be gen>
NEXTAUTH_URL=https://builder.example.com
NEXT_PUBLIC_VIEWER_URL=https://bot.example.com

SMTP_USERNAME=username
SMTP_PASSWORD=pass123
SMTP_HOST=smtp.host
SMTP_PORT=587
NEXT_PUBLIC_SMTP_FROM=Notifications <notifications@example.com>
SMTP_SECURE=false
SMTP_AUTH_DISABLED=false

S3_ACCESS_KEY=4566
S3_SECRET_KEY=ghuu
S3_BUCKET=tyre
#S3_PORT=9000
S3_ENDPOINT=fra1.digitaloceanspaces.com
S3_SSL=true
```

**Comment by itzomen** [comment] 2023-01-12 10:59
Haha, Still persists when I try to perform some actions:
Example when Inviting members:
_app-6124b8da55a13303.js:332 SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
POST https://typebot.example.com/api/workspaces/clcrgykxl0002mcyq6b4bojz9/invitations 500

**Comment by baptisteArno** [comment] 2023-01-12 13:17
Thank you for reporting this.

Can you export the bot that have the issue so that I can try on my side? (https://docs.typebot.io/editor/export_import)

Can I have access to your login page? (I won't do any action, just load the page and check the source) You can tell me the URL by email if you'd prefer: baptiste@typebot.io

**Comment by itzomen** [comment] 2023-01-12 13:23
> Thank you for reporting this.
> 
> Can you export the bot that have the issue so that I can try on my side? (https://docs.typebot.io/editor/export_import)
> 
> Can I have access to your login page? (I won't do any action, just load the page and check the source) You can tell me the URL by email if you'd prefer: [baptiste@typebot.io](mailto:baptiste@typebot.io)

Alright, sure sending that in a bit

**Comment by baptisteArno** [comment] 2023-01-12 13:40
How do you deploy typebot? With a docker-compose file? Do you insert environment variables correctly? Because I can see your public variables are not correctly populated:

<img width="692" alt="CleanShot 2023-01-12 at 14 37 37@2x" src="https://user-images.githubusercontent.com/16015833/212081613-8fcde31f-b0cc-4539-a371-09086af521b1.png">

(They are not prefixed with NEXT_PUBLIC_, that is expected, don't worry)

**Comment by itzomen** [comment] 2023-01-12 13:46
No, I deploy it manually.

Built the builder and the viewer, and then used pm2 to deploy both of them
on different ports.

Yeah, I noticed the env issue and I'm trying to fix it. I think docker
handles that and I'm trying to figure out how to add them myself. I made
sure my .env.local have all of them but not getting the variables to load.

Thanks for your help

**Comment by baptisteArno** [comment] 2023-01-12 14:20
That's probably the cause of all the mentioned issues. Deployment using docker is preferable.

But if we fix everything, we could then write a new "Deploy manually" documentation 👍

Can you pull the branch of [this PR](#238)?

Then, to build the app:

```sh
pnpm run build:apps
```

Then the start commands would be:

```sh
pnpm start
```

for both app. Can you tell me what would be the command with pm2?

**Comment by itzomen** [comment] 2023-01-12 14:32
Yeah, the Deploy manually is something I can do 

Additionally, I just figured that I need to add the env in the .env.docker manually; I guess that's what docker do when building the project.
I'm currently rebuilding the builder and the viewer to test it out. ( Aside: I noticed the builder takes lotta time to build lol😂 and I always have to pnpm build: builder then cd apps/builder && pnpm build before it works )

The pm2 command would be:
```bash
# this enables us to set the port
pm2 start --name=typebot pnpm -- next start -p 3004
# or 
pm2 start --name=typebot pnpm -- start
```

**Comment by itzomen** [comment] 2023-01-12 14:34
Okay, let me test this out with the edited .env.docker 

Then I will pull #238 and try

**Comment by itzomen** [comment] 2023-01-12 18:01
@baptisteArno I seriously don't know what is wrong, but I struggle to build the builder app each time. It gets often stuck or takes forever to build. It builds 2/10 times or when I'm lucky.

I've been trying to build it for close to 2hours now. Any hint would be great
Thanks

**Comment by itzomen** [comment] 2023-01-13 10:25
PR #238 solves the issues mentioned above

**Comment by baptisteArno** [comment] 2023-01-13 10:33
It will be closed once PR merged 👌

**Closed** 2023-01-14 14:39 UTC
Labels: Bug 🐛
