### ISSUE TITLE
Shared whatsapp webhook is not working

### ISSUE THREAD

**Issue by rodneyoliveira** [baptisteArno/typebot.io#1517] opened 2024-05-16 14:39 UTC
When I share a bot to listen whatsapp messages looks like its not working. Seems like webhook is "in trouble" to deal with requests received from Meta, based in log bellow

Follow bellow the logs I've got in typebot_viewer

Something went wrong ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "typebot"
    ],
    "message": "Required"
  },
    {
      "code": "invalid_type",
      "expected": "object",
      "received": "undefined",
      "path": [
        "linkedTypebots"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "currentTypebotId"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "object",
      "received": "undefined",
      "path": [
        "result"
      ],
      "message": "Required"
    }
  ]
      at get error [as error] (file:///app/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/index.mjs:538:31)
      at ZodEffects.parse (file:///app/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/index.mjs:638:22)
      at s (/app/apps/viewer/.next/server/pages/api/[...trpc].js:86:194467)
      at async h (/app/apps/viewer/.next/server/pages/api/[...trpc].js:88:2727)
      at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:420:30)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async outputMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:301:24)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.40.0/node_modules/@trpc/server/dist/index.mjs:456:32) {
    issues: [ [Object], [Object], [Object], [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object], [Object], [Object], [Object] ]
  }
}
Message is too old 1715869604000

**Comment by rodneyoliveira** [comment] 2024-05-16 14:42
In addition to reported bellow, I did a simple test creating a glitch webhook, to test conection with Meta and with glitch works fine.

**Comment by rodneyoliveira** [comment] 2024-05-18 00:20
sorry to bother, but, any clue what is going on?

**Comment by La-Rocca** [comment] 2024-05-19 13:31
Checked the Discord channel and the error wasn't fixed yet, maybe on the next version.
I am facing the same issue. How do you get the logs from the viewer? I am using conteiners.

**Comment by rodneyoliveira** [comment] 2024-05-19 15:08
The same here, my installation is under Easypanel that makes it easy.  Just connect to the container, and its shown. See bellow.

![Captura de Tela 2024-05-19 às 12 06 32](https://github.com/baptisteArno/typebot.io/assets/12769023/cf0f2d97-140b-49fc-87bc-86705d41eb1b)


In your case It depends what you are using to orchestrate(manage) your container. Each one has its way...I

**Comment by La-Rocca** [comment] 2024-05-19 16:37
Mine stop here:

<img width="281" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/146015131/011348e5-cb2f-40a5-beda-0bae7db5e2f2">

**Comment by baptisteArno** [comment] 2024-05-21 09:42
Duplicate of #1513

You will have to wait for next release to have this fix or you can pull `next` images

**Closed by baptisteArno** 2024-05-21 09:42 UTC

**Comment by baptisteArno** [comment] 2024-05-21 09:53
Releasing v2.25.2 now (should be available in max 30 min)
