### ISSUE TITLE
Vercel : Not authorized  Subscriptions are disabled.

### ISSUE THREAD

**Issue by alissonryan** [baptisteArno/typebot.io#650] opened 2023-07-26 22:51 UTC
Hello, I recently deployed to Vercel. I installed everything correctly with the environments but when logging in I get the message: "Not authorized Subscriptions are disabled."

I'm using as SMTP https://resend.com/
I am using Supabase as well.

This is the error log:

`[next-auth][error][SIGNIN_EMAIL_ERROR] 
https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
  error: {
    message: 'Email(s) could not be sent',
    stack: 'Error: Email(s) could not be sent\n' +
      '    at Object.sendVerificationRequest (/var/task/apps/builder/.next/server/chunks/5501.js:330:15)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async email (/var/task/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
      '    at async Object.signin (/var/task/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
      '    at async AuthHandler (/var/task/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/var/task/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async handler (/var/task/apps/builder/.next/server/chunks/5501.js:560:12)',
    name: 'Error'
  },
  providerId: 'email',
  message: 'Email(s) could not be sent'
}`

![Screenshot 2023-07-26 at 19 50 25](https://github.com/baptisteArno/typebot.io/assets/40619781/aaaa647a-b3e3-4fd6-a9f0-aed826ed5690)

by the log it accuses that it did not send, but I had already tested it with another SMTP from the hostinger and it accused the same error.

**Comment by baptisteArno** [comment] 2023-07-27 05:40
Hey, have you set up `SMTP_SECURE` to `true`? Because Resend want you to use port 465

**Comment by alissonryan** [comment] 2023-07-27 09:57
yes, I'm using all the settings that Resend requested. Putting the password as the api key, username as [resend] and the SMTP address and port.


As I said, before I had done a deploy, and I put the hostinger's smtp, which is where my domain is and even then it didn't work. I thought about deleting this one and doing one without login to see if it works. But first I wanted to solve it if it happens in another installation.

**Comment by baptisteArno** [comment] 2023-07-28 05:33
Ok, I managed to reproduce the error. That's when you are trying to send from another email address.

Try with `onboarding@resend.dev`, it should work.

I am closing as it is not an issue with Typebot 🙏

**Closed by baptisteArno** 2023-07-28 05:33 UTC
