### ISSUE TITLE
Create folder api returns error, but creates folder. Also creates non-unique named folders. 

### ISSUE THREAD

**Issue by magick93** [baptisteArno/typebot.io#1661] opened 2024-07-24 00:15 UTC
Hello

I'm using this api method - https://docs.typebot.io/api-reference/folder/create

The payload that I send is correct, based on the docs, and it does create the folder:

```ts
const payload = {
            "workspaceId": this.workspaceId,
            "folderName": group_question.group_question_id,
        };

        const options = {
            method: 'POST',
            headers: this.heaaders,
            body: JSON.stringify(payload)
        };
```

However, the response is:

```
        "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"null\",\n    \"received\": \"string\",\n    \"path\": [\n      \"typebot\",\n      \"folderId\"\n    ],\n    \"message\": \"Expected null, received string\"\n  }\n]"
```

Also, if I make multiple calls with the same payload, multiple folders are created with the same name.

This can be resolved using:

```sql
CREATE UNIQUE INDEX "DashboardFolder_name_parentFolderId_idx" ON "DashboardFolder" (name, COALESCE("parentFolderId", 'global'));
```

**Comment by baptisteArno** [comment] 2024-07-24 14:04
That's odd! I can't reproduce the issue 🤔

**Comment by baptisteArno** [comment] 2024-11-12 15:48
Closing. Feel free to re-open if you have more info

**Closed by baptisteArno** 2024-11-12 15:48 UTC
