### ISSUE TITLE
Option to filter results

### ISSUE THREAD

**Issue by radioextremosul** [baptisteArno/typebot.io#933] opened 2023-10-15 13:39 UTC
Option to filter fields by date, example from day x to day y

![Captura de tela de 2023-10-15 10-38-07](https://github.com/baptisteArno/typebot.io/assets/135563573/7615ae4e-74c8-4be2-a037-94105b52b93d)

**Comment by michaelvips** [comment] 2023-10-16 02:24
This shouldn't be in the issues category

**Comment by baptisteArno** [comment] 2023-10-16 13:16
Duplicate of https://github.com/baptisteArno/typebot.io/issues/372

**Closed by baptisteArno** 2023-10-16 13:16 UTC
