### ISSUE TITLE
OpenAI Invalid key length

### ISSUE THREAD

**Issue by CptPlastic** [baptisteArno/typebot.io#705] opened 2023-08-22 21:36 UTC
```
Aug 22 16:31:46 }
Aug 22 16:33:24 ... 8 lines matching cause stack trace ...
Aug 22 16:33:24 Something went wrong DataError: Invalid key length
Aug 22 16:33:24 [cause]: DOMException [DataError]: Invalid key length
Aug 22 16:33:24 at /app/code/builder/apps/builder/.next/server/chunks/4548.js:1691:124
Aug 22 16:33:24 at Object.aesImportKey (node:internal/crypto/aes:279:7)
Aug 22 16:33:24 at SubtleCrypto.importKey (node:internal/crypto/webcrypto:562:10)
Aug 22 16:33:24 at __node_internal_ (node:internal/util:509:10)
Aug 22 16:33:24 at async callRecursive (file:///app/code/builder/node_modules/.pnpm/@trpc+server@10.34.0/node_modules/@trpc/server/dist/index.mjs:452:32)
Aug 22 16:33:24 at async outputMiddleware (file:///app/code/builder/node_modules/.pnpm/@trpc+server@10.34.0/node_modules/@trpc/server/dist/index.mjs:297:24)
Aug 22 16:33:24 at async outputMiddleware (file:///app/code/builder/node_modules/.pnpm/@trpc+server@10.34.0/node_modules/@trpc/server/dist/index.mjs:297:24) {
Aug 22 16:33:24 at async resolveMiddleware (file:///app/code/builder/node_modules/.pnpm/@trpc+server@10.34.0/node_modules/@trpc/server/dist/index.mjs:416:30)
Aug 22 16:33:24 at encrypt (/app/code/builder/apps/builder/.next/server/chunks/5044.js:40:37)
Aug 22 16:33:24 at new DOMException (node:internal/per_context/domexception:53:5)
Aug 22 16:33:24 at new DOMException (node:internal/per_context/domexception:53:5)
Aug 22 16:33:24 at validateKeyLength (node:internal/crypto/aes:78:11)
Aug 22 16:33:24 code: 'INTERNAL_SERVER_ERROR',
Aug 22 16:33:24 name: 'TRPCError',
Aug 22 16:33:24 }
```

**Comment by baptisteArno** [comment] 2023-08-23 06:17
Duplicate of #672

**Closed by baptisteArno** 2023-08-23 06:17 UTC

**Comment by CptPlastic** [comment] 2023-08-23 18:42
@baptisteArno you marked this as a duplicate however there is no place to add this or see the key. It shows up as a file in Cloudron.

**Comment by CptPlastic** [comment] 2023-08-23 18:43
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/ac63a7cd-0dcf-41f2-9d1d-9756196ddfb3)

**Comment by CptPlastic** [comment] 2023-08-23 18:50
For anyone running into this issue here is how to fix this. Open a terminal.
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/78aef336-d9d1-449d-b392-e51ea8d1ee09)
Then run the cmd 
`openssl rand -base64 24 | tr -d '\n' ; echo`
replace that in the .encryption_secret file.
