### ISSUE TITLE
problem with typebot: check server logs to see relevant error message.

### ISSUE THREAD

**Issue by miscIick** [baptisteArno/typebot.io#1682] opened 2024-08-06 07:59 UTC
I've tried reinstalling several times to fix the code but it doesn't work, I even managed to get to the part to send an email but the email isn't sent, could you help me with this? Error: check server logs to see relevant error message. I will leave the error images and the code I am using
[docker-compose.txt](https://github.com/user-attachments/files/16507218/docker-compose.txt)
![Captura de tela 2024-08-04 170942](https://github.com/user-attachments/assets/8667fdd8-89c5-41d6-a485-529e2b1ed46f)
![Captura de tela 2024-08-04 172337](https://github.com/user-attachments/assets/a9feb5a3-ee9f-488e-b81e-f07083d33292)
![Captura de tela 2024-08-05 225214](https://github.com/user-attachments/assets/a0dd2a42-0ee8-48be-99b1-105f5b010e33)

**Comment by baptisteArno** [comment] 2024-08-12 13:19
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by paulozzy9** [comment] 2024-08-12 17:37
> Você pode fornecer os logs do servidor? Deve haver um erro claro aí.
> 
> Se você estiver hospedando-o com o docker. Digite este comando no seu terminal:
> 
> ```shell
> docker-compose logs
> ```
> 
> Cole todos os logs aqui para que possamos ajudá-lo adequadamente!

estou com mesmo problema, onde rodo esse comando tenho o  type instalado no portainer

**Comment by dionepereira** [comment] 2024-08-28 00:32
Eu verifiquei os logs, pelo que vi a conexão foi rejeitada pelo servidor de e-mail e não foi possivel o envio do email de confirmação de conta. Troque seu servidor smtp. No caso abaixo utilizei o servidor do google.

typebot-builder-1  |     name: 'Error'
typebot-builder-1  |   },
typebot-builder-1  |   providerId: 'email',
typebot-builder-1  |   message: 'Magic link email could not be sent. See error above.'
typebot-builder-1  | }
typebot-builder-1  | **Error: connect ECONNREFUSED 172.217.192.108:25**    
typebot-builder-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
typebot-builder-1  |   errno: -111,
typebot-builder-1  |   code: 'ESOCKET',
typebot-builder-1  |   syscall: 'connect',
typebot-builder-1  |   address: '172.217.192.108',
typebot-builder-1  |   port: 25,
typebot-builder-1  |   command: 'CONN'
typebot-builder-1  | }
typebot-builder-1  | **[next-auth][error][SIGNIN_EMAIL_ERROR]**
typebot-builder-1  | https://next-auth.js.org/errors#signin_email_error Magic link email could not be sent. See error above. {
typebot-builder-1  |   error: {
typebot-builder-1  |     message: '**Magic link email could not be sent. See error above**.',

**Comment by miscIick** [comment] 2024-08-28 22:09
Hello Batista, I'm hosting it on the Docker App, follow the image
![image](https://github.com/user-attachments/assets/8f9c1cc9-0872-40fd-9f28-5101b79a8211)
![image](https://github.com/user-attachments/assets/0cf98801-89fd-4060-bfb4-36c161e6d447)
PS C:\Users\walla\Desktop\docker-compose (1)> docker-compose logs
time="2024-08-28T19:05:18-03:00" level=warning msg="C:\\Users\\walla\\Desktop\\docker-compose (1)\\docker-compose.yml: `version` is obsolete"
typebot-viewer-1  | - event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
typebot-viewer-1  | - ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/viewer/public/__ENV.js'.
typebot-viewer-1  |    ▲ Next.js 14.1.0
typebot-viewer-1  |    - Local:        http://localhost:3000
typebot-viewer-1  |    - Network:      http://0.0.0.0:3000
typebot-viewer-1  |
typebot-viewer-1  |  ✓ Ready in 77ms
typebot-builder-1  | - event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
typebot-builder-1  | - ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/builder/public/__ENV.js'.
typebot-db-1       |
typebot-builder-1  | Waiting for 15s for database to be ready...
typebot-builder-1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder-1  | Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"
typebot-builder-1  |
typebot-builder-1  | 68 migrations found in prisma/migrations
typebot-builder-1  |
typebot-builder-1  |
typebot-builder-1  | No pending migrations to apply.
typebot-builder-1  |    ▲ Next.js 14.1.0
typebot-builder-1  |    - Local:        http://localhost:3000
typebot-builder-1  |    - Network:      http://0.0.0.0:3000
typebot-builder-1  |
typebot-builder-1  |  ✓ Ready in 867ms
typebot-builder-1  | prisma:info Starting a postgresql pool with 17 connections.
typebot-builder-1  | Error: self-signed certificate in certificate chain
typebot-builder-1  |     at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
typebot-builder-1  |     at TLSSocket.emit (node:events:519:28)
typebot-builder-1  |     at TLSSocket.emit (node:domain:488:12)
typebot-builder-1  |     at TLSSocket._finishInit (node:_tls_wrap:1085:8)
typebot-builder-1  |     at ssl.onhandshakedone (node:_tls_wrap:871:12) {
typebot-builder-1  |   code: 'ESOCKET',
minio-1            | MinIO Object Storage Server
minio-1            | Copyright: 2015-2024 MinIO, Inc.
minio-1            | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
minio-1            | Version: RELEASE.2024-08-03T04-33-23Z (go1.22.5 linux/amd64)
minio-1            |
minio-1            | API: http://172.19.0.2:9000  http://127.0.0.1:9000
minio-1            | WebUI: http://172.19.0.2:39219 http://127.0.0.1:39219
minio-1            |
minio-1            | Docs: https://min.io/docs/minio/linux/index.html
minio-1            | INFO:
minio-1            |  You are running an older version of MinIO released 3 weeks before the latest release
minio-1            |  Update: Run `mc admin update ALIAS`
minio-1            |
minio-1            |
typebot-db-1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
typebot-db-1       |
typebot-db-1       | 2024-08-28 22:03:31.174 UTC [1] LOG:  starting PostgreSQL 13.15 (Debian 13.15-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
typebot-builder-1  |   command: 'CONN'
typebot-builder-1  | }
typebot-builder-1  | [next-auth][error][SIGNIN_EMAIL_ERROR]
typebot-builder-1  | https://next-auth.js.org/errors#signin_email_error Magic link email could not be sent. See error above. {
typebot-builder-1  |   error: {
typebot-builder-1  |     message: 'Magic link email could not be sent. See error above.',
typebot-builder-1  |     stack: 'Error: Magic link email could not be sent. See error above.\n' +
typebot-builder-1  |       '    at Object.s [as sendVerificationRequest] (/app/apps/builder/.next/server/chunks/5043.js:1:4002)\n' +
typebot-builder-1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
mail-1             |     1 LOG: MAIN
mail-1             |     1   exim 4.89 daemon started: pid=1, -q30m, listening for SMTP on port 25 (IPv6 and IPv4)
typebot-builder-1  |       '    at async Promise.all (index 0)\n' +
typebot-builder-1  |       '    at async email (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
typebot-builder-1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
typebot-builder-1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/core/index.js:260:26)\n' +
typebot-builder-1  |       '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/next/index.js:22:19)\n' +
typebot-builder-1  |       '    at async z (/app/apps/builder/.next/server/chunks/5043.js:1:8413)\n' +
typebot-db-1       | 2024-08-28 22:03:31.191 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
typebot-db-1       | 2024-08-28 22:03:31.191 UTC [1] LOG:  listening on IPv6 address "::", port 5432
typebot-db-1       | 2024-08-28 22:03:31.196 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
typebot-db-1       | 2024-08-28 22:03:31.288 UTC [27] LOG:  database system was shut down at 2024-08-28 21:53:21 UTC
typebot-db-1       | 2024-08-28 22:03:31.317 UTC [1] LOG:  database system is ready to accept connections
typebot-db-1       | 2024-08-28 22:03:46.933 UTC [34] LOG:  could not receive data from client: Connection reset by peer
typebot-builder-1  |       '    at async K (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)\n' +
typebot-builder-1  |       '    at async U.render (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)',
typebot-builder-1  |     name: 'Error'
typebot-builder-1  |   },
typebot-builder-1  |   providerId: 'email',
typebot-builder-1  |   message: 'Magic link email could not be sent. See error above.'
typebot-builder-1  | }
createbuckets-1    | Added `minio` successfully.
createbuckets-1    | mc: <ERROR> Unable to make bucket `minio/typebot`. Your previous request to create the named bucket succeeded and you already own it.
createbuckets-1    | Access permission for `minio/typebot/public` is set to `public`
PS C:\Users\walla\Desktop\docker-compose (1)>

**Comment by miscIick** [comment] 2024-08-29 00:43
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    ports:
      - 3001:3000
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://192.168.18.2:3001
      - NEXT_PUBLIC_VIEWER_URL=http://192.168.18.2:3002
      - ENCRYPTION_SECRET=ayOGPLh6HcfBKg1dhRpNkJuVRD8v7kmm
      - ADMIN_EMAIL=wallacegsguerrero@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=wallacegsguerrero@gmail.com
      - SMTP_PASSWORD=zzvqkakfrawhmawg
      - SMTP_AUTH_DISABLED=false
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - NEXT_PUBLIC_SMTP_FROM=wallacegsguerrero@gmail.com.br
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.192.168.18.2

  typebot-viewer:
    ports:
      - 3002:3000
    image: baptistearno/typebot-viewer:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://192.168.18.2:3002
      - NEXTAUTH_URL=http://192.168.18.2:3001
      - ENCRYPTION_SECRET=ayOGPLh6HcfBKg1dhRpNkJuVRD8v7kmm
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=192.168.18.2

  mail:
    image: bytemark/smtp
    restart: always

  minio:
    labels:
      virtual.host: '192.168.18.2'
      virtual.port: '9000'
      virtual.tls-email: wallacegsguerrero@gmail.com
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "

volumes:
  db_data:
  s3_data:

**Comment by dionepereira** [comment] 2024-08-29 12:46
Worked for me:

      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=true
      - SMTP_USERNAME=usergmail@gmail.com
      - SMTP_PASSWORD= (Sign in with app passwords,not account password, see at google)
      - NEXT_PUBLIC_SMTP_FROM='Suporte Typebot' <usergmail@gmail.com>

**Comment by nickfromit** [comment] 2024-09-02 05:27
Olá, estou tendo a mesma dificuldade. Tentei tanto com smtp.hostinger.com e email typebot@link5g.cloud, quanto com o recomendado pelo Dione smtp.gmail.com e personaluser@gmail.com. Ainda sem MagicLink...

Hi, I'm having the same difficulty. I tried both with smtp.hostinger.com and email typebot@link5g.cloud, as well as the one recommended by Dione smtp.gmail.com and personaluser@gmail.com. Still no MagicLink...

**Comment by baptisteArno** [comment] 2024-09-02 08:24
Closing this as it seems the issue is not due to Typebot but more due invalid config. Feel free to reopen an issue if you have a clear reproduction to provide.

**Closed by baptisteArno** 2024-09-02 08:24 UTC

**Comment by miscIick** [comment] 2024-09-02 08:56
the logs is talking than the problem is in send of magic link how i can repair this. I was set this using the gmail SMTP and  this is correct email i am using gmail  and i am hosting typebot in my pc what i am should do if you don't can help us. who can ?

**Comment by Braido350** [comment] 2024-09-02 17:49
estou com o mesmo problema!

**Comment by dionepereira** [comment] 2024-09-02 19:10
> estou com o mesmo problema!

Eu estava com esse problema:

message: 'Magic link email could not be sent. See error above.'

Isso é configuração de SMTP. Você precisa ter uma conta no google com autenticação de dois fatores, procura a opção "Senhas de APP no google", gera uma senha de app e coloca na variavel SMTP_PASSWORD removendo os espaços em branco da senha.

  - SMTP_HOST=smtp.gmail.com
  - SMTP_PORT=587
  - SMTP_SECURE=true
  - SMTP_USERNAME=usergmail@gmail.com
  - SMTP_PASSWORD= (Sign in with app passwords,not account password, see at google)
  - NEXT_PUBLIC_SMTP_FROM='Suporte Typebot' <usergmail@gmail.com>

**Comment by Erick381** [comment] 2024-09-02 22:00
olá pessoal, estou como mesmo problema....
não consigo achar a solução....
alguém ja resolveu?

**Comment by Erick381** [comment] 2024-09-02 22:20
consegui resolver....
peguei esse video (https://www.youtube.com/watch?v=nFbZLX2U-5k) e gerei a senha do meu email pra colocar no typebot e deu certo!!!

**Comment by nickfromit** [comment] 2024-09-02 22:26
> consegui resolver.... peguei esse video (https://www.youtube.com/watch?v=nFbZLX2U-5k) e gerei a senha do meu email pra colocar no typebot e deu certo!!!

Infelizmente para mim nao funcionou. Pode mandar aqui a config do stack? secure true ou false? qual porta? usou email pessoal mesmo?

**Comment by miscIick** [comment] 2024-09-03 12:44
Eu já tentei de tudo trocar o servidor de email por outro por exemplo estou utilizando gmail tentei Yahoo mas mesmo assim não funciona sei lá e os 2 email estão com verificação de 2 fatores alem de estar utilizando a senha de app

**Comment by dionepereira** [comment] 2024-09-03 16:32
Abaixo o docker-compose.yml que funciona pra mim:

`version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    ports:
      - 3001:3000
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://192.168.0.0:3001
      - NEXT_PUBLIC_VIEWER_URL=http://192.168.0.0:3002
      - ENCRYPTION_SECRET=Ta0De1oCkgu7/zflbEPr4kRIofdKNlFj
      - ADMIN_EMAIL=seuemailaqui@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=seuemailaqui@gmail.com
      - SMTP_PASSWORD=senhaAppSemEspaco
      - SMTP_AUTH_DISABLED=false
      - SMTP_PORT=587
      - SMTP_SECURE=true
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXT_PUBLIC_SMTP_FROM=seuemailaqui@gmail.com
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.testedocker.com.br

  typebot-viewer:
    ports:
      - 3002:3000
    image: baptistearno/typebot-viewer:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://192.168.0.0:3002
      - NEXTAUTH_URL=http://192.168.0.0:3001
      - ENCRYPTION_SECRET=Ta0De1oCkgu7/zflbEPr4kRIofdKNlFj
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.testedocker.com.br

  mail:
    image: bytemark/smtp
    restart: always

  minio:
    labels:
      virtual.host: 'storage.testedocker.com.br'
      virtual.port: '9000'
      virtual.tls-email: 'seuemailaqui@gmail.com'
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "

volumes:
  db_data:
  s3_data:`

**Comment by dionepereira** [comment] 2024-09-03 16:33
> Eu já tentei de tudo trocar o servidor de email por outro por exemplo estou utilizando gmail tentei Yahoo mas mesmo assim não funciona sei lá e os 2 email estão com verificação de 2 fatores alem de estar utilizando a senha de app

Abaixo o docker-compose.yml que funciona pra mim, troque por suar informações e veja se funciona.

version: '3.3'
services:
typebot-db:
image: postgres:13
restart: always
volumes:
- db_data:/var/lib/postgresql/data
environment:
- POSTGRES_DB=typebot
- POSTGRES_PASSWORD=typebot

typebot-builder:
ports:
- 3001:3000
image: baptistearno/typebot-builder:latest
restart: always
depends_on:
- typebot-db
environment:
- DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
- NEXTAUTH_URL=http://192.168.0.0:3001/
- NEXT_PUBLIC_VIEWER_URL=http://192.168.0.0:3002/
- ENCRYPTION_SECRET=Ta0De1oCkgu7/zflbEPr4kRIofdKNlFj
- ADMIN_EMAIL=[seuemailaqui@gmail.com](mailto:seuemailaqui@gmail.com)
- SMTP_HOST=smtp.gmail.com
- SMTP_USERNAME=[seuemailaqui@gmail.com](mailto:seuemailaqui@gmail.com)
- SMTP_PASSWORD=senhaAppSemEspaco
- SMTP_AUTH_DISABLED=false
- SMTP_PORT=587
- SMTP_SECURE=true
- DEFAULT_WORKSPACE_PLAN=UNLIMITED
- NEXT_PUBLIC_SMTP_FROM=[seuemailaqui@gmail.com](mailto:seuemailaqui@gmail.com)
- S3_ACCESS_KEY=minio
- S3_SECRET_KEY=minio123
- S3_BUCKET=typebot
- S3_ENDPOINT=storage.testedocker.com.br

typebot-viewer:
ports:
- 3002:3000
image: baptistearno/typebot-viewer:latest
restart: always
environment:
- DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
- NEXT_PUBLIC_VIEWER_URL=http://192.168.0.0:3002/
- NEXTAUTH_URL=http://192.168.0.0:3001/
- ENCRYPTION_SECRET=Ta0De1oCkgu7/zflbEPr4kRIofdKNlFj
- S3_ACCESS_KEY=minio
- S3_SECRET_KEY=minio123
- S3_BUCKET=typebot
- S3_ENDPOINT=storage.testedocker.com.br

mail:
image: bytemark/smtp
restart: always

minio:
labels:
virtual.host: 'storage.testedocker.com.br'
virtual.port: '9000'
virtual.tls-email: '[seuemailaqui@gmail.com](mailto:seuemailaqui@gmail.com)'
image: minio/minio
command: server /data
ports:
- '9000:9000'
environment:
MINIO_ROOT_USER: minio
MINIO_ROOT_PASSWORD: minio123
volumes:
- s3_data:/data

createbuckets:
image: minio/mc
depends_on:
- minio
entrypoint: >
/bin/sh -c "
sleep 10;
/usr/bin/mc config host add minio http://minio:9000/ minio minio123;
/usr/bin/mc mb minio/typebot;
/usr/bin/mc anonymous set public minio/typebot/public;
exit 0;
"

volumes:
db_data:
s3_data:

**Comment by miscIick** [comment] 2024-09-03 21:40
dionepereiracCara tu é foda dms meu mano deu certinho muito obrigado!!!

**Comment by dionepereira** [comment] 2024-09-04 17:18
> dionepereiracCara tu é foda dms meu mano deu certinho muito obrigado!!!

Tmj, é nóis!!!

**Comment by Celks** [comment] 2025-02-21 16:58
Eu simplesmente resolvi trocando o email smtp para um antigo. Não sei porque o e-mail que tinha acabado de criar não estava funcionando.
