### ISSUE TITLE
Send Total Results Daily Digest Failure - Build Fail

### ISSUE THREAD

**Issue by jdefranco** [baptisteArno/typebot.io#790] opened 2023-09-08 00:45 UTC
### **Send Total Results Daily Digest Failure**

The "Send total results daily digest" workflow has encountered a failure. All jobs associated with this workflow have failed.

**Details:**

    Job Name: Send total results daily digest / send
    Duration: Failed in 1 minute and 47 seconds

**Error and Warnings:**

    **Error:**
        Process completed with exit code 1.

    **Warnings:**

        The actions actions/checkout@v2 and pnpm/action-setup@v2.2.2 are currently using node12, which is deprecated. They will soon be forced to run on node16 by default. [More Info](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/)

        The save-state command is deprecated and will be disabled in the near future. It's recommended to upgrade to using Environment Files. [More Info](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

        The set-output command is deprecated and will be disabled soon. It's advised to transition to using Environment Files. [More Info](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by baptisteArno** [comment] 2023-09-08 10:48
Duplicate of #788

**Closed by baptisteArno** 2023-09-08 10:48 UTC
