### ISSUE TITLE
Create an input that identifies any type of input

### ISSUE THREAD

**Issue by uelintonpessoa** [baptisteArno/typebot.io#1270] opened 2024-02-20 13:53 UTC
Hello @baptisteArno , could you create an input that can recognize the type of input, whether it is audio, text or file to be native?

It's a very important solution, because when integrating with the official WhatsApp API or unofficial WhatsApp API, generally the user sends a message anyway, and according to the flow we set up, the typebot ends up sending a text as an invalid message. , and we have this option to identify the type of input in this first input, we can filter and send it to the correct flow.

**Comment by baptisteArno** [comment] 2024-02-21 09:33
Duplicate of #854

**Closed by baptisteArno** 2024-02-21 09:33 UTC
