### ISSUE TITLE
Timeout for input blocks

### ISSUE THREAD

**Issue by heloineto** [baptisteArno/typebot.io#1905] opened 2024-11-28 17:31 UTC
**Is your feature request related to a problem? Please describe.**
Bots frequently lose customers when users become inactive due to confusion, distraction, or hesitation. This results in lost sales, poor user experience and bad reviews.

Currently, Typebot lacks a mechanism to handle user inactivity.

**Describe the solution you'd like**
Add a timeout field to input blocks, where the developer can define a fallback block to redirect the user after X seconds without a response.

**Describe alternatives you've considered**
A Cron Job that constantly monitors the conversations and checks if the user has not answered in a certain period of time. I have not implemented this and am not sure that it is possible. But regardless, this is very complex and not ideal.

**Comment by baptisteArno** [comment] 2024-11-30 16:34
Most likely a duplicate of https://github.com/baptisteArno/typebot.io/issues/1225

**Closed by baptisteArno** 2024-11-30 16:34 UTC
