### ISSUE TITLE
Webhooks failing blocked by CORS policy

### ISSUE THREAD

**Issue by kmain4** [baptisteArno/typebot.io#109] opened 2022-07-07 17:06 UTC
TypeBot webhooks are failing due to CORS policy:

```
Access to fetch at 'https://bot...../executeWebhook' from origin 'https://builder.......' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by kmain4** [comment] 2022-07-07 19:10
When executing a webhook in the Typebot Builder, the request fails.

Chrome reports:
```
A cross-origin resource sharing (CORS) request was blocked because it contained request headers that were neither CORS-safelisted (Accept, Accept-Language, Content-Language, Content-Type) nor allowed by the Access-Control-Allow-Headers response header of the associated preflight request.
To fix this issue, include the additional request headers you want to use in the Access-Control-Allow-Headers response header of the associated preflight request.

Disallowed header: content-type
```

**Comment by baptisteArno** [comment] 2022-09-01 06:27
Closing this as I couldn't reproduce and nobody else seems to have this issue for now.

Feel free to reopen if we gather more information.

**Closed by baptisteArno** 2022-09-01 06:27 UTC
