### ISSUE TITLE
Make chat answers editable

### ISSUE THREAD

**Issue by Cayllen** [baptisteArno/typebot.io#814] opened 2023-09-13 12:49 UTC
The following feature would be awesome:

 Make it possible for the user to (when allowed) scroll up the chat and change his answer. Especially for multiple-choice ones. If the user does that, the chat goes back to that point and all answers after are deleted - but ONLY till the point where the chain of conversion would change as it depends on the answer

**Comment by baptisteArno** [comment] 2023-09-18 15:37
Duplicate of #251

**Closed by baptisteArno** 2023-09-18 15:37 UTC
